# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Dev Deployment CI

on:
  push:
    branches: [master, dev, main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          npm-version: 8.5.x
      - name: Install dependencies
        run: npm install
      - name: Build App
        env:
          CI: false
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    # We specify that deploys needs to
    # finish before we create a release
    needs: build
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Git Client
        run: |
          git config --global user.email "sandeshsingh265@gmail.com"
          git config --global user.name "CI/CD"
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${github.ref})"
        id: extract_branch
      - name: Push artifacts
        run: |
          echo steps.extract_branch.outputs.branch
          git clone --depth 1 --single-branch -b ${{steps.extract_branch.outputs.branch}} git@github.com:${{github.repository}}.git deploy
          mv deploy/.git deploy-.git
          rm -rf deploy
          mkdir deploy
          mv deploy-.git deploy/.git
          cd deploy
          cp -R ../react-github-actions-build/* .
          git checkout -b deployment
          git add .
          git commit -m "Update Artifacts ${{github.run_number}}"
          git push -f origin deployment